// an array of objets for countries corresponding to their ISO 3166-1 alpha-2 codes and currencies
export const countries = [
  { name: "Nigeria", code: "NG", dial_code: "+234", currency: "NGN" },

  { name: "Afghanistan", code: "AF", dial_code: "+93", currency: "AFN" },
  { name: "Aland Islands", code: "AX", dial_code: "+358", currency: "EUR" },
  { name: "Albania", code: "AL", dial_code: "+355", currency: "ALL" },
  { name: "Algeria", code: "DZ", dial_code: "+213", currency: "DZD" },
  { name: "American Samoa", code: "AS", dial_code: "+1684", currency: "USD" },
  { name: "Andorra", code: "AD", dial_code: "+376", currency: "EUR" },
  { name: "Angola", code: "AO", dial_code: "+244", currency: "AOA" },
  { name: "Anguilla", code: "AI", dial_code: "+1264", currency: "XCD" },
  { name: "Antarctica", code: "AQ", dial_code: "+672", currency: "USD" },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    dial_code: "+1268",
    currency: "XCD",
  },
  { name: "Argentina", code: "AR", dial_code: "+54", currency: "ARS" },
  { name: "Armenia", code: "AM", dial_code: "+374", currency: "AMD" },
  { name: "Aruba", code: "AW", dial_code: "+297", currency: "AWG" },
  { name: "Australia", code: "AU", dial_code: "+61", currency: "AUD" },
  { name: "Austria", code: "AT", dial_code: "+43", currency: "EUR" },
  { name: "Azerbaijan", code: "AZ", dial_code: "+994", currency: "AZN" },
  { name: "Bahamas", code: "BS", dial_code: "+1242", currency: "BSD" },
  { name: "Bahrain", code: "BH", dial_code: "+973", currency: "BHD" },
  { name: "Bangladesh", code: "BD", dial_code: "+880", currency: "BDT" },
  { name: "Barbados", code: "BB", dial_code: "+1246", currency: "BBD" },
  { name: "Belarus", code: "BY", dial_code: "+375", currency: "BYN" },
  { name: "Belgium", code: "BE", dial_code: "+32", currency: "EUR" },
  { name: "Belize", code: "BZ", dial_code: "+501", currency: "BZD" },
  { name: "Benin", code: "BJ", dial_code: "+229", currency: "XOF" },
  { name: "Bermuda", code: "BM", dial_code: "+1441", currency: "BMD" },
  { name: "Bhutan", code: "BT", dial_code: "+975", currency: "BTN" },
  {
    name: "Bolivia, Plurinational State of",
    code: "BO",
    dial_code: "+591",
    currency: "BOB",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    dial_code: "+387",
    currency: "BAM",
  },
  { name: "Botswana", code: "BW", dial_code: "+267", currency: "BWP" },
  { name: "Brazil", code: "BR", dial_code: "+55", currency: "BRL" },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    dial_code: "+246",
    currency: "USD",
  },
  { name: "Brunei Darussalam", code: "BN", dial_code: "+673", currency: "BND" },
  { name: "Bulgaria", code: "BG", dial_code: "+359", currency: "BGN" },
  { name: "Burkina Faso", code: "BF", dial_code: "+226", currency: "XOF" },
  { name: "Burundi", code: "BI", dial_code: "+257", currency: "BIF" },
  { name: "Cambodia", code: "KH", dial_code: "+855", currency: "KHR" },
  { name: "Cameroon", code: "CM", dial_code: "+237", currency: "XAF" },
  { name: "Canada", code: "CA", dial_code: "+1", currency: "CAD" },
  { name: "Cape Verde", code: "CV", dial_code: "+238", currency: "CVE" },
  { name: "Cayman Islands", code: "KY", dial_code: "+ 345", currency: "KYD" },
  {
    name: "Central African Republic",
    code: "CF",
    dial_code: "+236",
    currency: "XAF",
  },
  { name: "Chad", code: "TD", dial_code: "+235", currency: "XAF" },
  { name: "Chile", code: "CL", dial_code: "+56", currency: "CLP" },
  { name: "China", code: "CN", dial_code: "+86", currency: "CNY" },
  { name: "Christmas Island", code: "CX", dial_code: "+61", currency: "AUD" },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    dial_code: "+61",
    currency: "AUD",
  },
  { name: "Colombia", code: "CO", dial_code: "+57", currency: "COP" },
  { name: "Comoros", code: "KM", dial_code: "+269", currency: "KMF" },
  { name: "Congo", code: "CG", dial_code: "+242", currency: "XAF" },
  {
    name: "Congo, The Democratic Republic of the",
    code: "CD",
    dial_code: "+243",
    currency: "CDF",
  },
  { name: "Cook Islands", code: "CK", dial_code: "+682", currency: "NZD" },
  { name: "Costa Rica", code: "CR", dial_code: "+506", currency: "CRC" },
  { name: "Cote d'Ivoire", code: "CI", dial_code: "+225", currency: "XOF" },
  { name: "Croatia", code: "HR", dial_code: "+385", currency: "HRK" },
  { name: "Cuba", code: "CU", dial_code: "+53", currency: "CUP" },
  { name: "Cyprus", code: "CY", dial_code: "+357", currency: "EUR" },
  { name: "Czech Republic", code: "CZ", dial_code: "+420", currency: "CZK" },
  { name: "Denmark", code: "DK", dial_code: "+45", currency: "DKK" },
  { name: "Djibouti", code: "DJ", dial_code: "+253", currency: "DJF" },
  { name: "Dominica", code: "DM", dial_code: "+1767", currency: "XCD" },
  {
    name: "Dominican Republic",
    code: "DO",
    dial_code: "+1849",
    currency: "DOP",
  },
  { name: "Ecuador", code: "EC", dial_code: "+593", currency: "USD" },
  { name: "Egypt", code: "EG", dial_code: "+20", currency: "EGP" },
  { name: "El Salvador", code: "SV", dial_code: "+503", currency: "USD" },
  { name: "Equatorial Guinea", code: "GQ", dial_code: "+240", currency: "XAF" },
  { name: "Eritrea", code: "ER", dial_code: "+291", currency: "ERN" },
  { name: "Estonia", code: "EE", dial_code: "+372", currency: "EUR" },
  { name: "Ethiopia", code: "ET", dial_code: "+251", currency: "ETB" },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    dial_code: "+500",
    currency: "FKP",
  },
  { name: "Faroe Islands", code: "FO", dial_code: "+298", currency: "DKK" },
  { name: "Fiji", code: "FJ", dial_code: "+679", currency: "FJD" },
  { name: "Finland", code: "FI", dial_code: "+358", currency: "EUR" },
  { name: "France", code: "FR", dial_code: "+33", currency: "EUR" },
  { name: "French Guiana", code: "GF", dial_code: "+594", currency: "EUR" },
  { name: "French Polynesia", code: "PF", dial_code: "+689", currency: "XPF" },
  {
    name: "French Southern Territories",
    code: "TF",
    dial_code: "+262",
    currency: "EUR",
  },
  { name: "Gabon", code: "GA", dial_code: "+241", currency: "XAF" },
  { name: "Gambia", code: "GM", dial_code: "+220", currency: "GMD" },
  { name: "Georgia", code: "GE", dial_code: "+995", currency: "GEL" },
  { name: "Germany", code: "DE", dial_code: "+49", currency: "EUR" },
  { name: "Ghana", code: "GH", dial_code: "+233", currency: "GHS" },
  { name: "Gibraltar", code: "GI", dial_code: "+350", currency: "GIP" },
  { name: "Greece", code: "GR", dial_code: "+30", currency: "EUR" },
  { name: "Greenland", code: "GL", dial_code: "+299", currency: "DKK" },
  { name: "Grenada", code: "GD", dial_code: "+1473", currency: "XCD" },
  { name: "Guadeloupe", code: "GP", dial_code: "+590", currency: "EUR" },
  { name: "Guam", code: "GU", dial_code: "+1671", currency: "USD" },
  { name: "Guatemala", code: "GT", dial_code: "+502", currency: "GTQ" },
  { name: "Guernsey", code: "GG", dial_code: "+44", currency: "GBP" },
  { name: "Guinea", code: "GN", dial_code: "+224", currency: "GNF" },
  { name: "Guinea-Bissau", code: "GW", dial_code: "+245", currency: "XOF" },
  { name: "Guyana", code: "GY", dial_code: "+595", currency: "GYD" },
  { name: "Haiti", code: "HT", dial_code: "+509", currency: "HTG" },
  {
    name: "Heard Island and McDonald Islands",
    code: "HM",
    dial_code: "+672",
    currency: "AUD",
  },
  { name: "Honduras", code: "HN", dial_code: "+504", currency: "HNL" },
  { name: "Hong Kong", code: "HK", dial_code: "+852", currency: "HKD" },
  { name: "Hungary", code: "HU", dial_code: "+36", currency: "HUF" },
  { name: "Iceland", code: "IS", dial_code: "+354", currency: "ISK" },
  { name: "India", code: "IN", dial_code: "+91", currency: "INR" },
  { name: "Indonesia", code: "ID", dial_code: "+62", currency: "IDR" },
  {
    name: "Iran, Islamic Republic of",
    code: "IR",
    dial_code: "+98",
    currency: "IRR",
  },
  { name: "Iraq", code: "IQ", dial_code: "+964", currency: "IQD" },
  { name: "Ireland", code: "IE", dial_code: "+353", currency: "EUR" },
  { name: "Isle of Man", code: "IM", dial_code: "+44", currency: "GBP" },
  { name: "Israel", code: "IL", dial_code: "+972", currency: "ILS" },
  { name: "Italy", code: "IT", dial_code: "+39", currency: "EUR" },
  { name: "Jamaica", code: "JM", dial_code: "+1876", currency: "JMD" },
  { name: "Japan", code: "JP", dial_code: "+81", currency: "JPY" },
  { name: "Jersey", code: "JE", dial_code: "+44", currency: "GBP" },
  { name: "Jordan", code: "JO", dial_code: "+962", currency: "JOD" },
  { name: "Kazakhstan", code: "KZ", dial_code: "+7", currency: "KZT" },
  { name: "Kenya", code: "KE", dial_code: "+254", currency: "KES" },
  { name: "Kiribati", code: "KI", dial_code: "+686", currency: "AUD" },
  {
    name: "Korea, Democratic People's Republic of",
    code: "KP",
    dial_code: "+850",
    currency: "KPW",
  },
  { name: "Korea, Republic of", code: "KR", dial_code: "+82", currency: "KRW" },
  { name: "Kuwait", code: "KW", dial_code: "+965", currency: "KWD" },
  { name: "Kyrgyzstan", code: "KG", dial_code: "+996", currency: "KGS" },
  {
    name: "Lao People's Democratic Republic",
    code: "LA",
    dial_code: "+856",
    currency: "LAK",
  },
  { name: "Latvia", code: "LV", dial_code: "+371", currency: "EUR" },
  { name: "Lebanon", code: "LB", dial_code: "+961", currency: "LBP" },
  { name: "Lesotho", code: "LS", dial_code: "+266", currency: "LSL" },
  { name: "Liberia", code: "LR", dial_code: "+231", currency: "LRD" },
  {
    name: "Libyan Arab Jamahiriya",
    code: "LY",
    dial_code: "+218",
    currency: "LYD",
  },
  { name: "Liechtenstein", code: "LI", dial_code: "+423", currency: "CHF" },
  { name: "Lithuania", code: "LT", dial_code: "+370", currency: "EUR" },
  { name: "Luxembourg", code: "LU", dial_code: "+352", currency: "EUR" },
  { name: "Macao", code: "MO", dial_code: "+853", currency: "MOP" },
  {
    name: "Macedonia, the Former Yugoslav Republic of",
    code: "MK",
    dial_code: "+389",
    currency: "MKD",
  },
  { name: "Madagascar", code: "MG", dial_code: "+261", currency: "MGA" },
  { name: "Malawi", code: "MW", dial_code: "+265", currency: "MWK" },
  { name: "Malaysia", code: "MY", dial_code: "+60", currency: "MYR" },
  { name: "Maldives", code: "MV", dial_code: "+960", currency: "MVR" },
  { name: "Mali", code: "ML", dial_code: "+223", currency: "XOF" },
  { name: "Malta", code: "MT", dial_code: "+356", currency: "EUR" },
  { name: "Marshall Islands", code: "MH", dial_code: "+692", currency: "USD" },
  { name: "Martinique", code: "MQ", dial_code: "+596", currency: "EUR" },
  { name: "Mauritania", code: "MR", dial_code: "+222", currency: "MRO" },
  { name: "Mauritius", code: "MU", dial_code: "+230", currency: "MUR" },
  { name: "Mayotte", code: "YT", dial_code: "+262", currency: "EUR" },
  { name: "Mexico", code: "MX", dial_code: "+52", currency: "MXN" },
  {
    name: "Micronesia, Federated States of",
    code: "FM",
    dial_code: "+691",
    currency: "USD",
  },
  {
    name: "Moldova, Republic of",
    code: "MD",
    dial_code: "+373",
    currency: "MDL",
  },
  { name: "Monaco", code: "MC", dial_code: "+377", currency: "EUR" },
  { name: "Mongolia", code: "MN", dial_code: "+976", currency: "MNT" },
  { name: "Montenegro", code: "ME", dial_code: "+382", currency: "EUR" },
  { name: "Montserrat", code: "MS", dial_code: "+1664", currency: "XCD" },
  { name: "Morocco", code: "MA", dial_code: "+212", currency: "MAD" },
  { name: "Mozambique", code: "MZ", dial_code: "+258", currency: "MZN" },
  { name: "Myanmar", code: "MM", dial_code: "+95", currency: "MMK" },
  { name: "Namibia", code: "NA", dial_code: "+264", currency: "NAD" },
  { name: "Nauru", code: "NR", dial_code: "+674", currency: "AUD" },
  { name: "Nepal", code: "NP", dial_code: "+977", currency: "NPR" },
  { name: "Netherlands", code: "NL", dial_code: "+31", currency: "EUR" },
  {
    name: "Netherlands Antilles",
    code: "AN",
    dial_code: "+599",
    currency: "ANG",
  },
  { name: "New Caledonia", code: "NC", dial_code: "+687", currency: "XPF" },
  { name: "New Zealand", code: "NZ", dial_code: "+64", currency: "NZD" },
  { name: "Nicaragua", code: "NI", dial_code: "+505", currency: "NIO" },
  { name: "Niger", code: "NE", dial_code: "+227", currency: "XOF" },
  { name: "Nigeria", code: "NG", dial_code: "+234", currency: "NGN" },
  { name: "Niue", code: "NU", dial_code: "+683", currency: "NZD" },
  { name: "Norfolk Island", code: "NF", dial_code: "+672", currency: "AUD" },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    dial_code: "+1670",
    currency: "USD",
  },
  { name: "Norway", code: "NO", dial_code: "+47", currency: "NOK" },
  { name: "Oman", code: "OM", dial_code: "+968", currency: "OMR" },
  { name: "Pakistan", code: "PK", dial_code: "+92", currency: "PKR" },
  { name: "Palau", code: "PW", dial_code: "+680", currency: "USD" },
  {
    name: "Palestinian Territory, Occupied",
    code: "PS",
    dial_code: "+970",
    currency: "ILS",
  },
  { name: "Panama", code: "PA", dial_code: "+507", currency: "PAB" },
  { name: "Papua New Guinea", code: "PG", dial_code: "+675", currency: "PGK" },
  { name: "Paraguay", code: "PY", dial_code: "+595", currency: "PYG" },
  { name: "Peru", code: "PE", dial_code: "+51", currency: "PEN" },
  { name: "Philippines", code: "PH", dial_code: "+63", currency: "PHP" },
  { name: "Pitcairn", code: "PN", dial_code: "+872", currency: "NZD" },
  { name: "Poland", code: "PL", dial_code: "+48", currency: "PLN" },
  { name: "Portugal", code: "PT", dial_code: "+351", currency: "EUR" },
  { name: "Puerto Rico", code: "PR", dial_code: "+1939", currency: "USD" },
  { name: "Qatar", code: "QA", dial_code: "+974", currency: "QAR" },
  { name: "Reunion", code: "RE", dial_code: "+262", currency: "EUR" },
  { name: "Romania", code: "RO", dial_code: "+40", currency: "RON" },
  { name: "Russia", code: "RU", dial_code: "+7", currency: "RUB" },
  { name: "Rwanda", code: "RW", dial_code: "+250", currency: "RWF" },
  { name: "Saint Helena", code: "SH", dial_code: "+290", currency: "SHP" },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    dial_code: "+1869",
    currency: "XCD",
  },
  { name: "Saint Lucia", code: "LC", dial_code: "+1758", currency: "XCD" },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    dial_code: "+508",
    currency: "EUR",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    dial_code: "+1784",
    currency: "XCD",
  },
  { name: "Samoa", code: "WS", dial_code: "+685", currency: "WST" },
  { name: "San Marino", code: "SM", dial_code: "+378", currency: "EUR" },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    dial_code: "+239",
    currency: "STD",
  },
  { name: "Saudi Arabia", code: "SA", dial_code: "+966", currency: "SAR" },
  { name: "Senegal", code: "SN", dial_code: "+221", currency: "XOF" },
  { name: "Serbia", code: "RS", dial_code: "+381", currency: "RSD" },
  { name: "Seychelles", code: "SC", dial_code: "+248", currency: "SCR" },
  { name: "Sierra Leone", code: "SL", dial_code: "+232", currency: "SLL" },
  { name: "Singapore", code: "SG", dial_code: "+65", currency: "SGD" },
  { name: "Slovakia", code: "SK", dial_code: "+421", currency: "EUR" },
  { name: "Slovenia", code: "SI", dial_code: "+386", currency: "EUR" },
  { name: "Solomon Islands", code: "SB", dial_code: "+677", currency: "SBD" },
  { name: "Somalia", code: "SO", dial_code: "+252", currency: "SOS" },
  { name: "South Africa", code: "ZA", dial_code: "+27", currency: "ZAR" },
  { name: "South Sudan", code: "SS", dial_code: "+211", currency: "SSP" },
  { name: "South Korea", code: "KR", dial_code: "+82", currency: "KRW" },
  { name: "Spain", code: "ES", dial_code: "+34", currency: "EUR" },
  { name: "Sri Lanka", code: "LK", dial_code: "+94", currency: "LKR" },
  { name: "Sudan", code: "SD", dial_code: "+249", currency: "SDG" },
  { name: "Suriname", code: "SR", dial_code: "+597", currency: "SRD" },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    dial_code: "+47",
    currency: "NOK",
  },
  { name: "Swaziland", code: "SZ", dial_code: "+268", currency: "SZL" },
  { name: "Sweden", code: "SE", dial_code: "+46", currency: "SEK" },
  { name: "Switzerland", code: "CH", dial_code: "+41", currency: "CHF" },
  { name: "Syria", code: "SY", dial_code: "+963", currency: "SYP" },
  { name: "Taiwan", code: "TW", dial_code: "+886", currency: "TWD" },
  { name: "Tajikistan", code: "TJ", dial_code: "+992", currency: "TJS" },
  { name: "Tanzania", code: "TZ", dial_code: "+255", currency: "TZS" },
  { name: "Thailand", code: "TH", dial_code: "+66", currency: "THB" },
  { name: "Timor-Leste", code: "TL", dial_code: "+670", currency: "USD" },
  { name: "Togo", code: "TG", dial_code: "+228", currency: "XOF" },
  { name: "Tokelau", code: "TK", dial_code: "+690", currency: "NZD" },
  { name: "Tonga", code: "TO", dial_code: "+676", currency: "TOP" },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    dial_code: "+1868",
    currency: "TTD",
  },
  { name: "Tunisia", code: "TN", dial_code: "+216", currency: "TND" },
  { name: "Turkey", code: "TR", dial_code: "+90", currency: "TRY" },
  { name: "Turkmenistan", code: "TM", dial_code: "+993", currency: "TMT" },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    dial_code: "+1649",
    currency: "USD",
  },
  { name: "Tuvalu", code: "TV", dial_code: "+688", currency: "AUD" },
  { name: "Uganda", code: "UG", dial_code: "+256", currency: "UGX" },
  { name: "Ukraine", code: "UA", dial_code: "+380", currency: "UAH" },
  {
    name: "United Arab Emirates",
    code: "AE",
    dial_code: "+971",
    currency: "AED",
  },
  { name: "United Kingdom", code: "GB", dial_code: "+44", currency: "GBP" },
  { name: "United States", code: "US", dial_code: "+1", currency: "USD" },
  { name: "Uruguay", code: "UY", dial_code: "+598", currency: "UYU" },
  { name: "Uzbekistan", code: "UZ", dial_code: "+998", currency: "UZS" },
  { name: "Vanuatu", code: "VU", dial_code: "+678", currency: "VUV" },
  { name: "Venezuela", code: "VE", dial_code: "+58", currency: "VEF" },
  { name: "Vietnam", code: "VN", dial_code: "+84", currency: "VND" },

  { name: "Wallis and Futuna", code: "WF", dial_code: "+681", currency: "XPF" },
  { name: "Western Sahara", code: "EH", dial_code: "+212", currency: "MAD" },
  { name: "Yemen", code: "YE", dial_code: "+967", currency: "YER" },
  { name: "Zambia", code: "ZM", dial_code: "+260", currency: "ZMK" },
  { name: "Zimbabwe", code: "ZW", dial_code: "+263", currency: "ZWL" },
];
