import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute top-0 w-full border-b py-2 min-h-[60px] flex items-center px-[30px] bg-[#FAFAFA]">
          <h2 className="text-2xl font-bold">Spend Guard</h2>
        </div>
        <div className="h-screen bg-[#E5E5E5] pt-[60px]">{children}</div>
      </body>
    </html>
  );
}
